### ISSUE TITLE
Jaspersoft-OAUTH2  integration fails when using PING Federate

### ISSUE THREAD

**Issue by arunkumar1981** [kmeadows1980/jasperserver#3]
Hi,
When we are trying to fetch the accesstoken from the PING Federate OAUTH server, server declines the request stating that "Client must not use more than one authentication method". 

It seems that in exchangeAuthorizationCodeForAccessToken function of OAuthPreAuthenticationFilter.java, we are passing client id and secret as parameters in both request header and body which I assume that server doesnt accept. 

I am not sure what OAUTH specification states about it.Is it an issue with PING ?
Else, Could you please let me know if it is okay for me to just remove header information from the requests.

Exception:
OAuthProblemException{error='invalid_client', description='The client MUST NOT use more than one authentication method in each request.', uri='null', state='null', scope='null', redirectUri='null', responseStatus=0, parameters={}}
        at org.apache.oltu.oauth2.common.exception.OAuthProblemException.error(OAuthProblemException.java:59)
        at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validateErrorResponse(OAuthClientValidator.java:63)
        at org.apache.oltu.oauth2.client.validator.OAuthClientValidator.validate(OAuthClientValidator.java:48)
        at org.apache.oltu.oauth2.client.response.OAuthClientResponse.validate(OAuthClientResponse.java:64)
        at org.apache.oltu.oauth2.client.response.OAuthClientResponse.init(OAuthClientResponse.java:59)
        at org.apache.oltu.oauth2.client.response.OAuthAccessTokenResponse.init(OAuthAccessTokenResponse.java:52)
        at org.apache.oltu.oauth2.client.response.OAuthClientResponseFactory.createCustomResponse(OAuthClientResponseFactory.java:60)
        at org.apache.oltu.oauth2.client.URLConnectionClient.execute(URLConnectionClient.java:111)
        at org.apache.oltu.oauth2.client.OAuthClient.accessToken(OAuthClient.java:65)

**Comment by kmeadows1980** [comment]
You can remove the basic authentication in the source.  

2 sections in the OauthPreAuthenticationFilter of source shown below:

 Map<String, String> headers = Utils.getBasicAuthorizationHeader(client_id, clientsecret);
		    //headers.put("Content-Type", "application/x-www-form-urlencoded");
accesstoken_request1.setHeaders(headers);


Some providers allow for multiple authentication types and some do not.  I will note to refactor this to the configuration file.

Thanks.
