### ISSUE TITLE
Keep getting an exception, server won't start

### ISSUE THREAD

**Issue by ozsynergy** [kmeadows1980/jasperserver#4]
I followed the instructions, tried two different oauth2 providers (Cognito and github).
I'm using jasperserver pro 6.4 from AWS marketplace.

and I keep getting this... any idea? .... :

2017-09-22 04:02:43,856 ERROR ContextLoader,localhost-startStop-1:336 - Context initialization failed
java.lang.NoClassDefFoundError: org/apache/oltu/oauth2/common/exception/OAuthSystemException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2595)
	at java.lang.Class.getDeclaredConstructors(Class.java:1914)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.determineCandidateConstructors(AutowiredAnnotationBeanPostProcessor.java:231)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.determineConstructorsFromBeanPostProcessors(AbstractAutowireCapableBeanFactory.java:1004)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:977)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:487)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:934)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5118)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5634)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:899)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:875)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:652)
	at org.apache.catalina.startup.HostConfig.deployDirectory(HostConfig.java:1296)
	at org.apache.catalina.startup.HostConfig$DeployDirectory.run(HostConfig.java:2038)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:473)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:622)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.oltu.oauth2.common.exception.OAuthSystemException
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1892)
	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1735)

**Comment by ozsynergy** [comment]
[root@ip lib]# ls -al *oltu*
-rw-r--r-- 1 root root 31167 Sep 21 04:43 org.apache.oltu.oauth2.client-0.31.jar
-rw-r--r-- 1 root root 33036 Sep 21 04:43 org.apache.oltu.oauth2.common-0.31.jar
[root@ip-10-2-0-118 lib]# pwd
/var/lib/tomcat7/webapps/jasperserver-pro/WEB-INF/lib


[root@ip WEB-INF]# ls -al applicationContext-externalAuth-oAuth.xml
-rw-r--r-- 1 root root 9031 Sep 22 03:57 applicationContext-externalAuth-oAuth.xml
[root@ip WEB-INF]# pwd
/var/lib/tomcat7/webapps/jasperserver-pro/WEB-INF

**Comment by sgwood63** [comment]
java.lang.NoClassDefFoundError: org/apache/oltu/oauth2/common/exception/OAuthSystemException

Looks like you are missing the Apache Oltu libraries in the WEB-INF/lib 

https://oltu.apache.org/

These JARs in the "binaries" directory of this project, or you can pull them in via maven or getting a Otlu distribution. Keith was using Otlu client v 0.31 in this project.

Sherman

**Comment by ozsynergy** [comment]
I found a fork with 6.4 binaries on spark-jaspersoft/jasperserver-oauth-saml... trying their compiled binaries the error goes away (so I'm assuming classes load) but the auth request doesn't go to oauth2 auth just gets done locally.

**Comment by kmeadows1980** [comment]
I would recommend you compile from the source code and you will need the apache oltu binaries.  All binaries outside of the JRS binaries are in the project.   There are updates to the source that are not in the compiled binaries.
